### PR TITLE
[PYTHON-4160] Add LlamaIndex

### PR DESCRIPTION
**Pull request by caseyclements**
This PR closes 4160. Adds new build-variant.

### CODE REVIEW

**Comment by caseyclements** [comment]
Can I add a `.gitignore` to this project? @Jibola

**Comment by Jibola** [comment]
> Can I add a `.gitignore` to this project? @Jibola

I'm guessing the .idea files aren't necessary?

**Comment by caseyclements** [comment]
> > Can I add a `.gitignore` to this project? @Jibola
> 
> I'm guessing the .idea files aren't necessary?

https://jira.mongodb.org/browse/PYTHON-4306

**Comment by caseyclements** [comment]
I removed the `.idea` directory. :)

**Review by Jibola — APPROVED** [review]
LGTM

**Pull request merged**
